### ISSUE TITLE
Can I use GMM-Demux for a combination of HTOs per sample?

### ISSUE THREAD

**Issue by sorjuela** [CHPGenetics/GMM-demux#1]
Hi,
From your paper I see that to remove multiplets, the assumption is that each sample corresponds to a single HTO right? I was wondering if I could also use your method for samples that correspond to multiple HTOs, e.g a setup like in figure 4 of the Zunder paper for mass cytometry https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4347881/figure/F4/ but for CITE-seq of course.

Best,
Stephany

**Comment by xhongyi** [comment]
This is certainly a possibility. While the current version does not support this. I will address it in the next update.

Judging from the work required, this function will come online in a week or two.

**Comment by sorjuela** [comment]
Cool, thanks!

**Comment by xhongyi** [comment]
Hi, the requested feature is now online.

Please checkout case 5b for an example.
