### ISSUE TITLE
GMM cannot find a viable solution that satisfies the droplet formation model. SSM rate estimation terminated.

### ISSUE THREAD

**Issue by VitorAguiar** [CHPGenetics/GMM-demux#6]
I get this error when using the -u option. Are there any options I could try?

Thank you!

```
$ GMM-demux filtered_feature_bc_matrix Hashtag1,Hashtag2,Hashtag3,Hashtag4,Hashtag5,Hashtag6 -u 13946                     
==============================GMM-Demux Initialization==============================
Confidence threshold: 0.8
Output directory: SSD_mtx
MSM-free droplets are stored in folder SSD_mtx 

GMM cannot find a viable solution that satisfies the droplet formation model. SSM rate estimation terminated.
```

**Comment by xhongyi** [comment]
Was 13946 the number of cells loaded to 10X or the number of cells harvested from the data?
Were you using 10X Chromium or Chromium X? GMM-Demux's SSM inference system were tuned for Chromium not Chromium X.
Could you provide the classification summary (how many singlets and doublets in total for each category)?

Thanks!

**Comment by xhongyi** [comment]
If you are out of options, you could also check out the GMM-Demux experiment planner at: http://54.152.221.82/exp_planner/

If you feed it with the loaded cell population size, it should be able to provide a rough estimation of the amount of total doublets.

Here I've made a screen shot of it. I'm not sure if it matches your results.

![image](https://user-images.githubusercontent.com/4156276/190923460-82d25dad-7cb3-43d3-b4b8-a0fe721605ec.png)
