### ISSUE TITLE
GMM-Demux installation error

### ISSUE THREAD

**Issue by mari-ga** [CHPGenetics/GMM-demux#9]
Hi!

First of all, thank you very much for this tool.
I've been using GMM-Demux without any problem, but some days ago, I encountered an error related to Sklearn when trying to install the package from pip. This is the error: 

```
Collecting sklearn (from GMM-Demux)
  Downloading sklearn-0.0.post12.tar.gz (2.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.
      
      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
```

It looks like a version of sklearn was deprecated. Have you seen this issue before? any suggestion? 

Thank you very much in advance.

**Comment by ghar1821** [comment]
Had the same issue. Solved it by cloning the github repo, change line 35 of `setup.py` from `sklearn` to `scikit-learn`.

Then install using:

```
python3 setup.py sdist bdist_wheel
pip3 install . 
```

**Comment by xhongyi** [comment]
Hi all,

Sorry that I just see this. Seems like sklearn is depreciated.

Will update the source code tonight.

Hongyi

**Comment by xhongyi** [comment]
> Had the same issue. Solved it by cloning the github repo, change line 35 of `setup.py` from `sklearn` to `scikit-learn`.
> 
> Then install using:
> 
> ```
> python3 setup.py sdist bdist_wheel
> pip3 install . 
> ```

Yes. Proper quick fix.

**Comment by xhongyi** [comment]
GMM-Demux has been updated to version 0.2.2.2 which fixes the scikit-learn issue and also updated an scipy API. Please let me know if there are further issues. If everything works, the issue will be closed in a few days.
